/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import conexion.Conexion;
import controlador.ClienteDAO;
import controlador.MetodoPagoDAO;
import controlador.ProductoDAO;
import controlador.VentaDAO;
import modelo.*;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author dayan
 */
public class VentanaVentas extends javax.swing.JFrame {
    
    private ProductoDAO productoDAO = new ProductoDAO();
    private ClienteDAO clienteDAO = new ClienteDAO();
    private VentaDAO ventaDAO = new VentaDAO();
    private MetodoPagoDAO metodoPagoDAO = new MetodoPagoDAO();
    private List<LineaDeVenta> carrito = new ArrayList<>();
    private List<Producto> productosEnCarrito = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaVentas.class.getName());

    /**
     * Creates new form VentanaVentas
     */
    public VentanaVentas() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Cómputo S.A.S - Módulo de Ventas");
        configurarTablas();
        cargarCatalogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCatalogo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        btnAgregarCarrito = new javax.swing.JButton();
        btnProcesarVenta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Búsqueda de Productos :");

        tablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCatalogo);

        jLabel2.setText("Carrito de Compras :");

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaCarrito);

        lblTotal.setText("Total: $0.0");

        jLabel3.setText("Nombre Cliente :");

        txtNombreCliente.setText("jTextField1");

        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta Débito", "Tarjeta Crédito" }));

        btnAgregarCarrito.setText("Agregar al Carrito");
        btnAgregarCarrito.addActionListener(this::btnAgregarCarritoActionPerformed);

        btnProcesarVenta.setText("Procesar Venta");
        btnProcesarVenta.addActionListener(this::btnProcesarVentaActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnProcesarVenta)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(325, 325, 325))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblTotal)
                    .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesarVenta)
                    .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
    int fila = tablaCatalogo.getSelectedRow();
    if (fila == -1) {
      javax.swing.JOptionPane.showMessageDialog(this,
        "Seleccione un producto del catálogo", "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);
      return;
    }

    String cantidadStr = javax.swing.JOptionPane.showInputDialog(this, 
     "¿Cuántas unidades desea agregar?");
    if (cantidadStr == null) return;

   try {
    int cantidad = Integer.parseInt(cantidadStr);
    int idProducto = (int) tablaCatalogo.getValueAt(fila, 0);
    Producto p = productoDAO.buscarPorId(idProducto);

    if (cantidad > p.getCantidadActual()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "No hay suficiente stock", "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    LineaDeVenta linea = new LineaDeVenta(carrito.size() + 1, p, cantidad);
    carrito.add(linea);

    DefaultTableModel modelCarrito = (DefaultTableModel) tablaCarrito.getModel();
    modelCarrito.addRow(new Object[]{
        p.getNombre(),
        cantidad,
        p.getPrecioVenta(),
        linea.getSubtotal()
    });
    actualizarTotal();

   } catch (NumberFormatException e) {
      javax.swing.JOptionPane.showMessageDialog(this,
        "Ingrese un número válido", "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed

    private void btnProcesarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarVentaActionPerformed
    if (carrito.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "El carrito está vacío", "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

    String nombreCliente = txtNombreCliente.getText();
    if (nombreCliente.isEmpty()) {
      javax.swing.JOptionPane.showMessageDialog(this,
        "Ingrese el nombre del cliente", "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);
      return;
    }

  try {
    // Buscar cliente existente o crear uno nuevo
    List<Cliente> clientes = clienteDAO.obtenerTodos();
    int idCliente = -1;
    for (Cliente c : clientes) {
      if (c.getNombre().equalsIgnoreCase(nombreCliente)) {
        idCliente = c.getIdCliente();
        break;
    }
  }
    if (idCliente == -1) {
       Cliente cliente = new Cliente(0, nombreCliente, "", "", "");
       clienteDAO.agregar(cliente);
       clientes = clienteDAO.obtenerTodos();
       idCliente = clientes.get(clientes.size() - 1).getIdCliente();
    }
    // Crear método de pago
    String metodoPago = cmbMetodoPago.getSelectedItem().toString();
    double total = 0;
    for (LineaDeVenta linea : carrito) {
        total += linea.getSubtotal();
    }
    total = total * 1.19;

    MetodoPago pago = null;
    switch (metodoPago) {
        case "Efectivo":
            pago = new Efectivo(total);
            break;
        case "Tarjeta Débito":
            String numDebito = javax.swing.JOptionPane.showInputDialog(
                this, "Ingrese número de tarjeta:");
            pago = new TarjetaDebito(total, numDebito, nombreCliente);
            break;
        case "Tarjeta Crédito":
            String numCredito = javax.swing.JOptionPane.showInputDialog(
                this, "Ingrese número de tarjeta:");
            String cuotasStr = javax.swing.JOptionPane.showInputDialog(
                this, "Ingrese número de cuotas:");
            int cuotas = Integer.parseInt(cuotasStr);
            pago = new TarjetaCredito(total, numCredito, nombreCliente, cuotas);
            break;
    }

    // Procesar pago
    if (pago != null && pago.procesarPago()) {
        int idMetodoPago = metodoPagoDAO.agregar(pago);

        // Crear venta
        String folio = Venta.generarFolio();
        Venta venta = new Venta(folio, idCliente, pago);
        for (LineaDeVenta linea : carrito) {
            venta.agregarLinea(linea);
        }

        // Verificar stock
        boolean hayPendientes = false;
        for (LineaDeVenta linea : carrito) {
            if (linea.getProducto().isEsBajoPedido()) {
                hayPendientes = true;
                break;
            }
        }

        venta.setEstatusVenta(hayPendientes ? "PENDIENTE" : "ENTREGADA");
        int idVenta = ventaDAO.agregar(venta, idMetodoPago);
        ventaDAO.agregarLineas(idVenta, carrito);

        // Mostrar documentos
        String documentos = venta.generarFactura() + "\n\n" + 
                           venta.generarGarantia() + "\n\n" + 
                           venta.generarManifiesto();

        javax.swing.JTextArea textArea = new javax.swing.JTextArea(documentos);
        textArea.setEditable(false);
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(600, 400));
        javax.swing.JOptionPane.showMessageDialog(this, scrollPane,
            "Documentos de Venta - Folio: " + folio,
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Limpiar carrito
        carrito.clear();
        ((DefaultTableModel) tablaCarrito.getModel()).setRowCount(0);
        lblTotal.setText("Total: $0.0");
        txtNombreCliente.setText("");
        cargarCatalogo();
    }

   } catch (Exception e) {
      javax.swing.JOptionPane.showMessageDialog(this,
        "Error al procesar venta: " + e.getMessage(), "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btnProcesarVentaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    String busqueda = txtBuscarProducto.getText().toLowerCase();
    DefaultTableModel model = (DefaultTableModel) tablaCatalogo.getModel();
    model.setRowCount(0);
    List<Producto> lista = productoDAO.obtenerTodos();
    for (Producto p : lista) {
      if (p.getNombre().toLowerCase().contains(busqueda) && p.getCantidadActual() > 0) {
        model.addRow(new Object[]{
            p.getIdProducto(),
            p.getNombre(),
            p.getTipoProducto(),
            p.getPrecioVenta(),
            p.getCantidadActual()
         });
       }
     }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    VentanaPrincipal ventana = new VentanaPrincipal();
    ventana.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

private void configurarTablas() {
    DefaultTableModel modelCatalogo = new DefaultTableModel();
    modelCatalogo.addColumn("ID");
    modelCatalogo.addColumn("Nombre");
    modelCatalogo.addColumn("Tipo");
    modelCatalogo.addColumn("Precio");
    modelCatalogo.addColumn("Stock");
    tablaCatalogo.setModel(modelCatalogo);

    DefaultTableModel modelCarrito = new DefaultTableModel();
    modelCarrito.addColumn("Nombre");
    modelCarrito.addColumn("Cantidad");
    modelCarrito.addColumn("Precio Unit.");
    modelCarrito.addColumn("Subtotal");
    tablaCarrito.setModel(modelCarrito);
}

private void cargarCatalogo() {
    DefaultTableModel model = (DefaultTableModel) tablaCatalogo.getModel();
    model.setRowCount(0);
    List<Producto> lista = productoDAO.obtenerTodos();
    for (Producto p : lista) {
        if (p.getCantidadActual() > 0) {
            model.addRow(new Object[]{
                p.getIdProducto(),
                p.getNombre(),
                p.getTipoProducto(),
                p.getPrecioVenta(),
                p.getCantidadActual()
            });
        }
    }
}

private void actualizarTotal() {
    double total = 0;
    for (LineaDeVenta linea : carrito) {
        total += linea.getSubtotal();
    }
    lblTotal.setText("Total: $" + String.format("%.2f", total * 1.19));
} 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaVentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnProcesarVenta;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTable tablaCatalogo;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
